---
# Prepare systems for install

- hosts: all
  gather_facts: no
  
  tasks:

  - name: Prepull images for Master Nodes
    docker_image:
      name: "{{item}}"
      state: present
    with_items:
      - docker.io/openshift/origin-template-service-broker:v3.11.0
      - docker.io/openshift/origin-service-catalog:v3.11.0
      - docker.io/openshift/origin-console:v3.11.0
      - docker.io/openshift/origin-web-console:v3.11.0
      - docker.io/openshift/origin-control-plane:v3.11
      - docker.io/openshift/origin-control-plane:v3.11.0
      - docker.io/openshift/origin-node:v3.11
      - docker.io/openshift/origin-deployer:v3.11.0
      - docker.io/openshift/origin-pod:v3.11
      - docker.io/openshift/origin-pod:v3.11.0
      - quay.io/coreos/etcd:v3.2.22
    when: openshift_node_group_name == 'node-config-master'

  - name: Prepull images for Infra Nodes
    docker_image:
      name: "{{item}}"
      state: present
    with_items:
      - docker.io/openshift/oauth-proxy:v1.1.0
      - docker.io/openshift/origin-docker-registry:v3.11.0
      - docker.io/grafana/grafana:5.2.1
      - quay.io/coreos/prometheus-operator:v0.23.2
      - quay.io/coreos/prometheus-config-reloader:v0.23.2
      - quay.io/coreos/cluster-monitoring-operator:v0.1.1
      - docker.io/openshift/origin-haproxy-router:v3.11.0
      - docker.io/openshift/origin-haproxy-router:v3.11
      - docker.io/openshift/origin-deployer:v3.11.0
      - docker.io/openshift/origin-node:v3.11
      - docker.io/openshift/origin-pod:v3.11
      - docker.io/openshift/origin-pod:v3.11.0
    when: openshift_node_group_name == 'node-config-infra'

  - name: Prepull images for App Nodes
    docker_image:
      name: "{{item}}"
      state: present
    with_items:
      - docker.io/openshift/origin-node:v3.11
      - docker.io/openshift/origin-pod:v3.11
      - docker.io/openshift/origin-pod:v3.11.0
    when: openshift_node_group_name == 'node-config-compute'

